// <auto-generated />
using Eterna.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eterna.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250817194151_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eterna.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Web Design"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobile App"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Branding"
                        });
                });

            modelBuilder.Entity("Eterna.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Portfolios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A modern and responsive website design for a tech company.",
                            ImageUrl = "portfolio-1.webp",
                            Title = "Modern Website Design"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "A secure and user-friendly mobile banking application.",
                            ImageUrl = "portfolio-2.webp",
                            Title = "Mobile Banking App"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Complete brand identity design for a startup company.",
                            ImageUrl = "portfolio-3.webp",
                            Title = "Brand Identity Design"
                        });
                });

            modelBuilder.Entity("Eterna.Models.PortfolioImg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioImgs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "portfolio-1.webp",
                            PortfolioId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "portfolio-4.webp",
                            PortfolioId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "portfolio-7.webp",
                            PortfolioId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "portfolio-2.webp",
                            PortfolioId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "portfolio-5.webp",
                            PortfolioId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "portfolio-3.webp",
                            PortfolioId = 3
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "portfolio-6.webp",
                            PortfolioId = 3
                        });
                });

            modelBuilder.Entity("Eterna.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("Eterna.Models.Portfolio", b =>
                {
                    b.HasOne("Eterna.Models.Category", "Category")
                        .WithMany("Portfolios")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Eterna.Models.PortfolioImg", b =>
                {
                    b.HasOne("Eterna.Models.Portfolio", "Portfolio")
                        .WithMany("PortfolioImgs")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Eterna.Models.Category", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("Eterna.Models.Portfolio", b =>
                {
                    b.Navigation("PortfolioImgs");
                });
#pragma warning restore 612, 618
        }
    }
}
